apiVersion: v1
kind: Service
metadata:
  name: lifecycle-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    name: lifecycle-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle-service-deployment
spec:
  selector:
    matchLabels:
      name: lifecycle-service
  replicas: 1
  template:
    metadata:
      labels:
        name: lifecycle-service
    spec:
      containers:
        - name: lifecycle-service
          image: cratekube/lifecycle-service:local
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /app/kube/kubeconfig
              name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            path: /var/lib/cratekube/kubeconfig